### ISSUE TITLE
Wrong shared struct address get in a "How to write a bootloader from scratch"

### ISSUE THREAD

**Issue by vpetrigo** [memfault/interrupt#171]
Hello,

First of all thank you for the article about the bootloader! 😄 

I would like to point out [that pointer assignment](https://github.com/memfault/interrupt/blame/e6c41bd5263500137cbabe80946c8e14f879868d/_posts/2019-08-13-how-to-write-a-bootloader-from-scratch.md#L480).

If we consider GNU LD, then to get proper access of a `shared_data` variable, we should use `&`:
```c
struct shared_data *sd = (struct shared_data *)&_shared_data_stat;
```

instead of accessing external variable by value like it is in the article:

```c
struct shared_data *sd = (struct shared_data *)_shared_data_stat;
```

**Comment by v-barshaw** [comment]
And it should be spelt _shared_data_start, not _shared_data_stat .
