### ISSUE TITLE
Renode example compiler warning

### ISSUE THREAD

**Issue by IvanVnucec** [memfault/interrupt#249]
I've cloned repo and tried to build Renode example in `/example/renode` with `make` command and the following compiler warning occured:
```c
renode-example.c:53:5: warning: no previous prototype for '_write' [-Wmissing-prototypes]
   53 | int _write(int file, char *ptr, int len)
      |     ^~~~~~
```

To fix the warning I've added function prototype
```c
int _write(int file, char *ptr, int len);
```
to the top of the `renode-example.c` file.

I can add pull req to resolve this issue.

INFO:  
Compiler version `arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]`

**Comment by noahp** [comment]
Thank you for posting this issue! I believe this is closed by #268
