### ISSUE TITLE
firmware-watchdog-best-practices, section `Configuration Reset Behavior` has the wrong datasheet excerpt

### ISSUE THREAD

**Issue by flaik-wayne** [memfault/interrupt#271]
The section `1. Configuration Reset Behavior` https://interrupt.memfault.com/blog/firmware-watchdog-best-practices#1-configuration-reset-behavior has a snip from the datasheet but it seems to be the wrong section.

![image](https://user-images.githubusercontent.com/106936944/175770223-b29edbb6-0ded-45e8-8e12-08000359d73a.png)

This same image is used again (different URL though) later in the section `4. RESETREAS` https://interrupt.memfault.com/blog/firmware-watchdog-best-practices#4-resetreas

**Comment by chrisc11** [comment]
Thanks for the report @flaik-wayne -- I've corrected this with the correct section in #273
