### ISSUE TITLE
Consider adjusting link color to differentiate from bold text 

### ISSUE THREAD

**Issue by mattkelly** [memfault/interrupt#29]
Maybe it's just my monitor or my eyes, but I have a really hard time distinguishing links from plain bold text, e.g.:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/248713/61488008-32334780-a975-11e9-8d0c-ea8b76b948a8.png">

I love the look of the blog overall, but IMO a slightly lighter blue would be helpful for link text.

**Comment by tyhoff** [comment]
Thanks for the suggestion @mattkelly! I've committed a fix.
