### ISSUE TITLE
Topic tags

### ISSUE THREAD

**Issue by iiontchev** [memfault/interrupt#58]
Consider adding 'topic tags' to the posts. This way, when the number of posts increases it will be easier to read/find all the posts related to a particular topic.

P.S. I really enjoy reading the blog. Good job and keep going. :)

**Comment by franc0is** [comment]
Thanks for the suggestion, Iliia! We've implemented topic tags, and have been using them for post series (e.g. https://interrupt.memfault.com/blog/tag/zero-to-main), but we'll go through and add other tags (and a tag list) soon.

**Comment by iiontchev** [comment]
Thank you for the clarification Francois. I couldn't tell that "From zero to main()" was a tag. I'm closing the issue as per your comment that tags and tag lists will be added soon.
