### ISSUE TITLE
Newer VSCode plugin for Cortex Devices

### ISSUE THREAD

**Issue by haneefdm** [memfault/interrupt#60]
You might want to update item #20 in your reference links. The link you have is okay but probably obsolete. There is a new plugin that is based on the one you reference that is much more specific/advanced for Cortex devices.

https://marketplace.visualstudio.com/items?itemName=marus25.cortex-debug

I am one of the maintainers.

**Comment by franc0is** [comment]
Hi @haneefdm, thanks for the note! Could you point out which pot you are referencing? We'll fix it right up!

**Comment by haneefdm** [comment]
I apologize I did not link to the proper article/section. The blog/article that I was referencing was...

https://interrupt.memfault.com/blog/a-deep-dive-into-arm-cortex-m-debug-interfaces#useful-reference-links

It is item number 20 in the `Useful Reference Links` section that I was trying to point out.

**Comment by franc0is** [comment]
I decided to add your plugin as an additional link rather than replace the original since it is a separate plugin, not a new version of the existing one. It's in review at #62

**Comment by haneefdm** [comment]
Thanks.
